language: php
php:
- 7
- 5.6
- 5.5
- hhvm
- nightly
matrix:
  allow_failures:
  - php: hhvm
  - php: nightly
before_script:
- composer selfupdate
- composer clearcache
- composer install --no-interaction --prefer-dist
script:
- "./vendor/bin/phpunit"
notifications:
  email:
    recipients:
    - david.verholen@brandung.de
    - daniel.rose@brandung.de
    on_success: never
    on_failure: always